### ISSUE TITLE
Translating from German to English and other languages

### ISSUE THREAD

**Issue by heptocat** [PSeminarKryptographie/MonkeyCrypt#16]
This is a very beginner friendly issue made especially in celebration of the Hacktoberfest :jack_o_lantern: 

As you might have noticed MonkeyCrypt is all in German … :beers: We would like to make MonkeyCrypt available in many other languages though. And this is where you come in. In the folder: src/text/ you can find the folder en which has a lot of German texts in it. The aim is to fill this folder with English texts. So:

+ fork the repository
+ open a txt file
+ replace the German text with an English translation **OR**
+ correct the English text with what you think is a better translation
+ submit a pull request

The original German texts (to compare translations) can be found in the folder *src/text* in the subfolders *did* or *sup*.
If you'd like to translate MonkeyCrypt into another language, you can copy the whole folder en, rename it, and start the same procedure.

**Don't forget to check out the guidelines on CONTRIBUTING.md**

**Comment by Arya04** [comment]
which text files/folder needs to be translated? and how should they be translated? just a simple google translate?

**Comment by heptocat** [comment]
The folder *src/text/en* can be translated into English. It has to subfolders, *did* and *hilfe*. The first includes html pages, so the translation has to be done between the html code. The second folder has txts in it.

It's important that the meaning is still the same in a translation, and that it sounds natural. So maybe a google translate should then be checked manually so that it has the same meaning of the german text.

**Comment by Arya04** [comment]
so create new txt files? or just replace the txt within the ones that are already inside it? if i make new files what do i name them?

**Comment by heptocat** [comment]
The folder _en_ includes all files that the German folder includes as well. So you can replace these files with a file with your translation. if you should notice that a file exists in the German folder (src/text) but not in the English one (src/text/en), you can add this file to the English folder by naming it exactly what it's called in the German one.

Hope this helped to explain better.

**Comment by Arya04** [comment]
sounds good, ill work on this!

**Comment by Leocardoso94** [comment]
Nice, I'll work on pt-br translate

**Comment by Leocardoso94** [comment]
#21 

I translated the texts to pt-br, please check when possible.

**Comment by petia-davidova** [comment]
How about Bulgarian translation :) Not the most popular language though :/

**Comment by heptocat** [comment]
Hi @petia-davidova ! We're keen on any translation, there are no boring languages ;).

We used both eclipse and netbeans to make the project. However it is possible to simply compile the source code manually if you have a java compiler, or run an ant-build. If you check in later I will add some more detailed instructions in README.md

If you don't want to compile it yourself you can download a .jar release (See *releases* on the top bar). This release however is not completely up-to-date.

**Comment by albertotn** [comment]
working for translation in italian!

**Comment by geekfred** [comment]
I can do Spanish for you.
