### ISSUE TITLE
Submitting Ideas - For beginners - practice pull requests

### ISSUE THREAD

**Issue by heptocat** [PSeminarKryptographie/MonkeyCrypt#17]
This issue was made especially for beginners and the Hacktoberfest!

We're looking for ideas on how to improve our MonkeyCrypt project!
Just fork our repository, play around with MonkeyCrypt for a while, and if you can think of something cool - or crazy - we could add, edit the *IDEAS.md* file, and submit a pull request!

Feel free to reply if you're a beginner  you need some help with pull requests and github in general.

If this issue is to boring for you, check out our other beginner friendly issue, #16

**Comment by andreybleme** [comment]
Hi @heptocat! 
What do you mean when you guys say you want to "translate to other languages"? Translate the code implementation? The readme.md file? I can help with both english and portuguese!

**Comment by heptocat** [comment]
Hi!
By translating we mean translating the explanatory texts that we have in our program. You can read more in issue #16. Most texts are still just in German now, but if you check back in when we have several English ones as well, having a Portuguese version would be really cool!

**Comment by Sineth-N** [comment]
Hi!
Mind if I add some improvements to the ideas ?
